"""sync missing tables

Revision ID: 58f3c14121da
Revises: 0003_phase22_email_actions
Create Date: 2026-07-02 12:33:20.904086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58f3c14121da'
down_revision: Union[str, None] = '0003_phase22_email_actions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('conv_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_call_logs_id'), 'agent_call_logs', ['id'], unique=False)
    op.create_index(op.f('ix_agent_call_logs_user_id'), 'agent_call_logs', ['user_id'], unique=False)
    op.create_table('google_calendar_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('google_email', sa.String(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_calendar_tokens_id'), 'google_calendar_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_google_calendar_tokens_user_id'), 'google_calendar_tokens', ['user_id'], unique=True)
    op.create_table('proactive_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proactive_insights_created_at'), 'proactive_insights', ['created_at'], unique=False)
    op.create_index(op.f('ix_proactive_insights_id'), 'proactive_insights', ['id'], unique=False)
    op.create_index(op.f('ix_proactive_insights_user_id'), 'proactive_insights', ['user_id'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(), nullable=False),
    sa.Column('auth', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_id'), 'push_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('routines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('trigger_phrase', sa.String(), nullable=False),
    sa.Column('steps', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routines_id'), 'routines', ['id'], unique=False)
    op.create_index(op.f('ix_routines_user_id'), 'routines', ['user_id'], unique=False)
    op.create_table('timers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('remaining_seconds_at_pause', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timers_id'), 'timers', ['id'], unique=False)
    op.create_index(op.f('ix_timers_user_id'), 'timers', ['user_id'], unique=False)
    op.create_table('user_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fact', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('source_conv', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_facts_id'), 'user_facts', ['id'], unique=False)
    op.create_index(op.f('ix_user_facts_user_id'), 'user_facts', ['user_id'], unique=False)
    op.create_table('reminders_fired',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reminder_id', sa.Integer(), nullable=True),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reminder_id')
    )
    op.create_index(op.f('ix_reminders_fired_id'), 'reminders_fired', ['id'], unique=False)
    op.alter_column('project_links', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_links', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_reminders_fired_id'), table_name='reminders_fired')
    op.drop_table('reminders_fired')
    op.drop_index(op.f('ix_user_facts_user_id'), table_name='user_facts')
    op.drop_index(op.f('ix_user_facts_id'), table_name='user_facts')
    op.drop_table('user_facts')
    op.drop_index(op.f('ix_timers_user_id'), table_name='timers')
    op.drop_index(op.f('ix_timers_id'), table_name='timers')
    op.drop_table('timers')
    op.drop_index(op.f('ix_routines_user_id'), table_name='routines')
    op.drop_index(op.f('ix_routines_id'), table_name='routines')
    op.drop_table('routines')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_proactive_insights_user_id'), table_name='proactive_insights')
    op.drop_index(op.f('ix_proactive_insights_id'), table_name='proactive_insights')
    op.drop_index(op.f('ix_proactive_insights_created_at'), table_name='proactive_insights')
    op.drop_table('proactive_insights')
    op.drop_index(op.f('ix_google_calendar_tokens_user_id'), table_name='google_calendar_tokens')
    op.drop_index(op.f('ix_google_calendar_tokens_id'), table_name='google_calendar_tokens')
    op.drop_table('google_calendar_tokens')
    op.drop_index(op.f('ix_agent_call_logs_user_id'), table_name='agent_call_logs')
    op.drop_index(op.f('ix_agent_call_logs_id'), table_name='agent_call_logs')
    op.drop_table('agent_call_logs')
    # ### end Alembic commands ###
